# Generated by Django 2.0.7 on 2018-09-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictmodel',
            name='model_type',
            field=models.CharField(choices=[('lr', 'Logistic regression'), ('cr', 'Cox regression'), ('ntcp', 'NTCP model')], max_length=100),
        ),
    ]
