# Generated by Django 2.0.7 on 2018-10-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_predictmodel_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField()),
            ],
        ),
    ]
