# Generated by Django 2.0.7 on 2018-10-01 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_scoretemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictmodel',
            name='score_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='predict.ScoreTemplate'),
        ),
        migrations.AddField(
            model_name='scoretemplate',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
