# Generated by Django 2.0.7 on 2018-10-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_auto_20181001_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictmodel',
            name='references',
            field=models.TextField(blank=True, null=True, verbose_name='References'),
        ),
    ]
