# Generated by Django 2.0.7 on 2018-10-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0006_auto_20181001_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuousregressionvariable',
            name='max',
            field=models.FloatField(verbose_name='Max'),
        ),
        migrations.AlterField(
            model_name='continuousregressionvariable',
            name='min',
            field=models.FloatField(verbose_name='Min'),
        ),
    ]
