# Generated by Django 2.0.7 on 2018-10-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0007_auto_20181001_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
