# Generated by Django 2.0.7 on 2018-10-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0009_auto_20181020_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuousregressionvariable',
            name='scale_center',
            field=models.FloatField(blank=True, null=True, verbose_name='Coeffient centre'),
        ),
        migrations.AlterField(
            model_name='predictmodel',
            name='model_type',
            field=models.CharField(choices=[('lrm', 'Logistic regression'), ('lm', 'Linear regression'), ('cr', 'Cox regression'), ('ntcp', 'NTCP model')], max_length=100),
        ),
    ]
