# Generated by Django 2.0.7 on 2018-11-20 16:27

from django.conf import settings
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('predict', '0010_auto_20181020_2206'),
    ]
