# Generated by Django 2.0.7 on 2018-11-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0011_auto_20181120_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictmodel',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
