# Generated by Django 2.1.3 on 2018-12-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0012_predictmodel_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictmodel',
            name='model_type',
            field=models.CharField(choices=[('lrm', 'Logistic regression'), ('lm', 'Linear regression'), ('cr', 'Cox regression'), ('ntcp', 'NTCP model'), ('seg', 'Segmentation model')], max_length=100),
        ),
    ]
